export const SOLUTIONS = [
  {
    slug: "hiring-recruitment", title: "Hiring & Recruitment",
    shortDescription: "Manage job openings, candidates, interviews, and offers from one place.",
    headline: "Build great teams with a faster, more organized hiring process",
    description: "Keep every stage of recruitment connected—from publishing a role and reviewing applicants to scheduling interviews and rolling out offers.",
    features: ["Job and vacancy management", "Candidate pipeline", "Interview scheduling", "Offer and onboarding workflow"],
    outcomes: ["Shorter time to hire", "A better candidate experience", "Clear hiring visibility"],
    steps: ["Create a job opening", "Review and shortlist candidates", "Schedule interview rounds", "Send an offer and begin onboarding"],
  },
  {
    slug: "attendance-management", title: "Attendance Management",
    shortDescription: "Track employee check-ins, working hours, late arrivals, and attendance trends.",
    headline: "Make employee attendance accurate, simple, and transparent",
    description: "Capture attendance in real time, maintain reliable records, and give employees and managers a clear view of working hours.",
    features: ["Digital check-in and check-out", "Working-hours tracking", "Late and absence records", "Attendance reports"],
    outcomes: ["Accurate attendance data", "Fewer manual corrections", "Better workforce visibility"],
    steps: ["Set attendance policies", "Record daily attendance", "Review exceptions", "Export payroll-ready reports"],
  },
  {
    slug: "shift-management", title: "Shift Management",
    shortDescription: "Plan shifts, assign employees, and keep every team properly staffed.",
    headline: "Create balanced shift schedules without the daily coordination",
    description: "Build and publish schedules, manage shift changes, and see staffing coverage before gaps affect business operations.",
    features: ["Flexible shift templates", "Employee scheduling", "Shift swaps and changes", "Coverage visibility"],
    outcomes: ["Fewer scheduling conflicts", "Balanced staffing", "Clearer team communication"],
    steps: ["Create shift templates", "Assign team members", "Publish the schedule", "Manage changes in real time"],
  },
  {
    slug: "leave-management", title: "Leave Management",
    shortDescription: "Simplify leave requests, approvals, balances, and holiday planning.",
    headline: "Give employees a clear and effortless leave experience",
    description: "Automate leave workflows so employees can request time off easily and managers can approve it with full team availability context.",
    features: ["Custom leave policies", "Self-service requests", "Approval workflows", "Leave balance and calendar"],
    outcomes: ["Faster approvals", "Accurate leave balances", "Better workforce planning"],
    steps: ["Configure leave policies", "Submit a leave request", "Review team availability", "Approve and update balances"],
  },
  {
    slug: "payroll-management", title: "Payroll Management",
    shortDescription: "Process salaries, deductions, bonuses, and payslips with confidence.",
    headline: "Run accurate and timely payroll from one secure workspace",
    description: "Bring attendance, leave, salary structures, additions, and deductions together for a dependable payroll process every month.",
    features: ["Salary structures", "Automated payroll calculations", "Deductions and bonuses", "Digital payslips"],
    outcomes: ["Fewer payroll errors", "On-time salary processing", "Transparent employee records"],
    steps: ["Set employee salary details", "Import attendance and leave", "Review payroll calculations", "Finalize and issue payslips"],
  },
  {
    slug: "performance-management", title: "Performance Management",
    shortDescription: "Align goals, reviews, and feedback to help every employee grow.",
    headline: "Turn performance conversations into continuous progress",
    description: "Set measurable goals, run consistent review cycles, and create a shared record of feedback and employee development.",
    features: ["Goals and key results", "Review cycles", "Continuous feedback", "Performance insights"],
    outcomes: ["Aligned employee goals", "Fairer evaluations", "Stronger professional growth"],
    steps: ["Define goals and expectations", "Track ongoing progress", "Collect meaningful feedback", "Complete reviews and growth plans"],
  },
  {
    slug: "organization-employee", title: "Organization & Employee",
    shortDescription: "Keep employee profiles, documents, roles, and reporting lines organized.",
    headline: "Create one reliable source of truth for your organization",
    description: "Maintain a structured employee directory and organization chart with the information teams need throughout the employee lifecycle.",
    features: ["Employee profiles", "Organization structure", "Role and department records", "Document management"],
    outcomes: ["Centralized employee data", "Clear reporting lines", "Simpler HR administration"],
    steps: ["Set up departments and roles", "Add employee records", "Build reporting relationships", "Maintain documents and changes"],
  },
  {
    slug: "accounts-finance", title: "Accounts & Finance",
    shortDescription: "Keep financial records, transactions, and business reporting under control.",
    headline: "Bring clarity and control to everyday business finance",
    description: "Organize financial activity in a connected system that helps your team maintain accurate records and make informed decisions.",
    features: ["Transaction records", "Income and expense tracking", "Account summaries", "Financial insights"],
    outcomes: ["Cleaner financial data", "Faster reconciliation", "Better business decisions"],
    steps: ["Configure accounts", "Record transactions", "Review financial activity", "Analyze and report"],
  },
  {
    slug: "business-operations", title: "Business Operations",
    shortDescription: "Manage invoices, expenses, and financial reports in one streamlined workspace.",
    headline: "Keep essential business operations connected and moving",
    description: "Create professional invoices, record and approve expenses, and use financial reports to understand business performance at a glance.",
    highlights: ["Invoices", "Expenses", "Financial Reports"],
    features: ["Invoice creation and tracking", "Expense capture and approvals", "Financial reports", "Operational overview"],
    outcomes: ["Faster invoicing", "Controlled business spending", "Clear financial visibility"],
    steps: ["Create and send invoices", "Record business expenses", "Review and approve entries", "Generate financial reports"],
  },
];

export const getSolutionBySlug = (slug) => SOLUTIONS.find((solution) => solution.slug === slug);
