export const SOLUTIONS = [
  {
    slug: "project-organizer",
    title: "Project Organizer",
    shortDescription: "Turn complex initiatives into clear plans, owners, and milestones.",
    headline: "Keep every project organized from kickoff to delivery",
    description: "Bring timelines, responsibilities, files, and progress into one focused workspace so teams always know what comes next.",
    features: ["Milestones and project phases", "Clear owners and due dates", "Centralized project updates", "Real-time progress visibility"],
    outcomes: ["Fewer missed deadlines", "Clear accountability", "Faster project delivery"],
    steps: ["Create a project workspace", "Break work into milestones", "Assign owners and timelines", "Track delivery in real time"],
  },
  {
    slug: "online-project-board",
    title: "Online Project Board",
    shortDescription: "Visualize priorities, blockers, and delivery status in one shared board.",
    headline: "Give every team a live view of project progress",
    description: "Plan and monitor work on a collaborative board that keeps priorities visible and conversations connected to execution.",
    features: ["Flexible project views", "Drag-and-drop prioritization", "Status and blocker tracking", "Shared team visibility"],
    outcomes: ["Better team alignment", "Faster status reviews", "Less manual reporting"],
    steps: ["Choose a project layout", "Add tasks and priorities", "Move work through stages", "Review progress together"],
  },
  {
    slug: "task-board",
    title: "Task Board",
    shortDescription: "Capture, assign, and complete daily tasks without losing context.",
    headline: "Move tasks from idea to done with complete clarity",
    description: "Create an easy-to-follow workflow where every task has an owner, priority, deadline, and visible status.",
    features: ["Custom task stages", "Priority and due-date controls", "Comments and attachments", "Task-level activity history"],
    outcomes: ["Fewer dropped tasks", "Quicker handoffs", "Visible ownership"],
    steps: ["Capture incoming work", "Set priority and owner", "Collaborate in context", "Complete and review"],
  },
  {
    slug: "work-organizer",
    title: "Work Organizer",
    shortDescription: "Coordinate recurring and one-off work across people and departments.",
    headline: "Organize team workloads without the operational noise",
    description: "Standardize how work is requested, assigned, and tracked while keeping workloads balanced across your organization.",
    features: ["Structured work requests", "Workload overview", "Recurring assignments", "Department-level filters"],
    outcomes: ["Balanced workloads", "Consistent processes", "Less coordination overhead"],
    steps: ["Collect work requests", "Review team capacity", "Assign and schedule", "Monitor completion"],
  },
  {
    slug: "day-organizer",
    title: "Day Organizer",
    shortDescription: "Build a realistic daily plan around priorities, meetings, and deadlines.",
    headline: "Help every employee make the most of their day",
    description: "Combine today’s tasks, scheduled work, and urgent priorities in a clean daily view designed for focus.",
    features: ["Daily priority list", "Schedule-aware planning", "Quick task capture", "End-of-day review"],
    outcomes: ["More focused days", "Better prioritization", "Less context switching"],
    steps: ["Review today’s workload", "Choose key priorities", "Work through a clear plan", "Carry forward what remains"],
  },
  {
    slug: "online-task-manager",
    title: "Online Task Manager",
    shortDescription: "Manage team tasks securely from anywhere and on any device.",
    headline: "Keep distributed teams connected to the work that matters",
    description: "Give teams a reliable online workspace to assign tasks, share updates, and keep delivery moving wherever they work.",
    features: ["Cloud-based task access", "Instant status updates", "Team notifications", "Search and smart filters"],
    outcomes: ["Reliable remote execution", "Faster updates", "One source of truth"],
    steps: ["Add your team", "Create and assign tasks", "Share live updates", "Track completion anywhere"],
  },
  {
    slug: "work-board",
    title: "Work Board",
    shortDescription: "See active work, capacity, and bottlenecks across the business.",
    headline: "Turn operational activity into an actionable overview",
    description: "Use a shared work board to understand what is moving, what is blocked, and where attention is needed next.",
    features: ["Cross-team work overview", "Capacity indicators", "Blocker highlighting", "Custom board filters"],
    outcomes: ["Earlier risk detection", "Smarter resourcing", "Clear operational health"],
    steps: ["Connect team workflows", "Configure board views", "Identify bottlenecks", "Rebalance and deliver"],
  },
  {
    slug: "digital-daily-planner",
    title: "Digital Daily Planner",
    shortDescription: "Plan focused days and connect personal priorities with team goals.",
    headline: "A calmer, smarter way to plan every working day",
    description: "Replace scattered notes with a structured digital planner that turns priorities into an achievable daily schedule.",
    features: ["Personal daily agenda", "Priority time blocks", "Task and goal linking", "Progress reflections"],
    outcomes: ["Intentional planning", "Higher personal focus", "Steady goal progress"],
    steps: ["Set daily goals", "Arrange focused blocks", "Complete planned work", "Reflect and prepare"],
  },
  {
    slug: "time-manager",
    title: "Time Manager",
    shortDescription: "Understand where time goes and improve planning with useful insights.",
    headline: "Make team time visible, accountable, and valuable",
    description: "Track work time with minimal effort, compare estimates with reality, and use the insights to plan more accurately.",
    features: ["Simple time tracking", "Project and task timesheets", "Estimate-versus-actual reports", "Utilization insights"],
    outcomes: ["More accurate estimates", "Better utilization", "Transparent reporting"],
    steps: ["Start tracking work", "Categorize recorded time", "Review team insights", "Improve future planning"],
  },
];

export const getSolutionBySlug = (slug) => SOLUTIONS.find((solution) => solution.slug === slug);
